### PR TITLE
basic support for quotes and escape sequences

### PR DESCRIPTION
**Pull request by patriziobruno**
I had issues using CSV from graphite's summarize(), as the values contained quotes

### CODE REVIEW

**Comment by jdbranham** [comment]
Thanks @patriziobruno !
I ran into the same issue this morning and added a regex replace.
One other issue, is that I'm persisting the predicted values back to graphite, so I can compare them visually in Grafana, but since the target now contains functions, I've added an 'alias' parameter to the PersistentGraphitePredictor. 

I'll check my changes in and let me know if this resolves your issue, before I merge this pull request.

Thanks for checking this out, and the contribution!

**Comment by jdbranham** [comment]
Also the README is out of date, but you probably already noticed that.
What type of use-case do you have?
Are you trying to predict future values?
Or use the boolean classification?

**Comment by patriziobruno** [comment]
Hi @jdbranham,

The pull request is to fix the missing support for quotes in CSV parsing and I see no reference of it in README. Why would I update the README in the context of this PR?
And about the use-case, what difference would it make if I'm doing linear-regression or classification? Again, I just need the CSV parsing routines to support quotes, whatever I'm going to do next with the parsed data.

**Comment by jdbranham** [comment]
Just curious about your use-case - nothing to do with the PR.

I mentioned the README, because I hadn't updated it with the latest features but looks like you figured it out.

**Comment by jdbranham** [comment]
I merged, but found this to be incompatible, so had to revert

**Pull request merged**
